use std::fmt;

#[derive(Debug, Clone, Copy)]
pub enum Mode {
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Accumulator,
    Immediate,
    Implied,
    Indirect,
    IndirectX,
    IndirectY,
    Relative,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
}

impl fmt::Display for Mode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

#[derive(Debug)]
pub enum Name {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
}

impl fmt::Display for Name {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

#[derive(Debug)]
pub struct Opcode {
    pub mode: Mode,
    pub name: Name,
    pub code: u8,
    pub bytes: u8,
}

impl<'a> Opcode {
    /// gets an opcode by its hex code
    pub fn get_by_code(code: u8) -> Option<&'a Opcode> {
        OPCODES.iter().find(|o| o.code == code)
    }
}

static OPCODES: [Opcode; 151] = [Opcode {
                                     code: 0x00,
                                     name: Name::BRK,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x01,
                                     name: Name::ORA,
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x05,
                                     name: Name::ORA,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x06,
                                     name: Name::ASL,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x08,
                                     name: Name::PHP,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x09,
                                     name: Name::ORA,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x0A,
                                     name: Name::ASL,
                                     mode: Mode::Accumulator,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x0D,
                                     name: Name::ORA,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x0E,
                                     name: Name::ASL,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x10,
                                     name: Name::BPL,
                                     mode: Mode::Relative,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x11,
                                     name: Name::ORA,
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x15,
                                     name: Name::ORA,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x16,
                                     name: Name::ASL,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x18,
                                     name: Name::CLC,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x19,
                                     name: Name::ORA,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x1D,
                                     name: Name::ORA,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x1E,
                                     name: Name::ASL,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x20,
                                     name: Name::JSR,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x21,
                                     name: Name::AND,
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x24,
                                     name: Name::BIT,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x25,
                                     name: Name::AND,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x26,
                                     name: Name::ROL,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x28,
                                     name: Name::PLP,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x29,
                                     name: Name::AND,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x2A,
                                     name: Name::ROL,
                                     mode: Mode::Accumulator,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x2C,
                                     name: Name::BIT,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x2D,
                                     name: Name::AND,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x2E,
                                     name: Name::ROL,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x30,
                                     name: Name::BMI,
                                     mode: Mode::Relative,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x31,
                                     name: Name::AND,
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x35,
                                     name: Name::AND,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x36,
                                     name: Name::ROL,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x38,
                                     name: Name::SEC,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x39,
                                     name: Name::AND,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x3D,
                                     name: Name::AND,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x3E,
                                     name: Name::ROL,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x40,
                                     name: Name::RTI,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x41,
                                     name: Name::EOR,
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x45,
                                     name: Name::EOR,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x46,
                                     name: Name::LSR,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x48,
                                     name: Name::PHA,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x49,
                                     name: Name::EOR,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x4A,
                                     name: Name::LSR,
                                     mode: Mode::Accumulator,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x4C,
                                     name: Name::JMP,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x4D,
                                     name: Name::EOR,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x4E,
                                     name: Name::LSR,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x50,
                                     name: Name::BVC,
                                     mode: Mode::Relative,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x51,
                                     name: Name::EOR,
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x55,
                                     name: Name::EOR,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x56,
                                     name: Name::LSR,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x58,
                                     name: Name::CLI,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x59,
                                     name: Name::EOR,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x5D,
                                     name: Name::EOR,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x5E,
                                     name: Name::LSR,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x60,
                                     name: Name::RTS,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x61,
                                     name: Name::ADC,
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x65,
                                     name: Name::ADC,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x66,
                                     name: Name::ROR,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x68,
                                     name: Name::PLA,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x69,
                                     name: Name::ADC,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x6A,
                                     name: Name::ROR,
                                     mode: Mode::Accumulator,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x6C,
                                     name: Name::JMP,
                                     mode: Mode::Indirect,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x6D,
                                     name: Name::ADC,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x6E,
                                     name: Name::ROR,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x70,
                                     name: Name::BVS,
                                     mode: Mode::Relative,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x71,
                                     name: Name::ADC,
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x75,
                                     name: Name::ADC,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x76,
                                     name: Name::ROR,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x78,
                                     name: Name::SEI,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x79,
                                     name: Name::ADC,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x7D,
                                     name: Name::ADC,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x7E,
                                     name: Name::ROR,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x81,
                                     name: Name::STA,
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x84,
                                     name: Name::STY,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x85,
                                     name: Name::STA,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x86,
                                     name: Name::STX,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x88,
                                     name: Name::DEY,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x8A,
                                     name: Name::TXA,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x8C,
                                     name: Name::STY,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x8D,
                                     name: Name::STA,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x8E,
                                     name: Name::STX,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x90,
                                     name: Name::BCC,
                                     mode: Mode::Relative,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x91,
                                     name: Name::STA,
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x94,
                                     name: Name::STY,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x95,
                                     name: Name::STA,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x96,
                                     name: Name::STX,
                                     mode: Mode::ZeroPageY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0x98,
                                     name: Name::TYA,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x99,
                                     name: Name::STA,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0x9A,
                                     name: Name::TXS,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0x9D,
                                     name: Name::STA,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xA0,
                                     name: Name::LDY,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xA1,
                                     name: Name::LDA,
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xA2,
                                     name: Name::LDX,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xA4,
                                     name: Name::LDY,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xA5,
                                     name: Name::LDA,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xA6,
                                     name: Name::LDX,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xA8,
                                     name: Name::TAY,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xA9,
                                     name: Name::LDA,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xAA,
                                     name: Name::TAX,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xAC,
                                     name: Name::LDY,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xAD,
                                     name: Name::LDA,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xAE,
                                     name: Name::LDX,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xB0,
                                     name: Name::BCS,
                                     mode: Mode::Relative,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xB1,
                                     name: Name::LDA,
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xB4,
                                     name: Name::LDY,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xB5,
                                     name: Name::LDA,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xB6,
                                     name: Name::LDX,
                                     mode: Mode::ZeroPageY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xB8,
                                     name: Name::CLV,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xB9,
                                     name: Name::LDA,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xBA,
                                     name: Name::TSX,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xBC,
                                     name: Name::LDY,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xBD,
                                     name: Name::LDA,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xBE,
                                     name: Name::LDX,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xC0,
                                     name: Name::CPY,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xC1,
                                     name: Name::CMP,
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xC4,
                                     name: Name::CPY,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xC5,
                                     name: Name::CMP,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xC6,
                                     name: Name::DEC,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xC8,
                                     name: Name::INY,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xC9,
                                     name: Name::CMP,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xCA,
                                     name: Name::DEX,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xCC,
                                     name: Name::CPY,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xCD,
                                     name: Name::CMP,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xCE,
                                     name: Name::DEC,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xD0,
                                     name: Name::BNE,
                                     mode: Mode::Relative,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xD1,
                                     name: Name::CMP,
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xD5,
                                     name: Name::CMP,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xD6,
                                     name: Name::DEC,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xD8,
                                     name: Name::CLD,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xD9,
                                     name: Name::CMP,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xDD,
                                     name: Name::CMP,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xDE,
                                     name: Name::DEC,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xE0,
                                     name: Name::CPX,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xE1,
                                     name: Name::SBC,
                                     mode: Mode::IndirectX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xE4,
                                     name: Name::CPX,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xE5,
                                     name: Name::SBC,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xE6,
                                     name: Name::INC,
                                     mode: Mode::ZeroPage,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xE8,
                                     name: Name::INX,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xE9,
                                     name: Name::SBC,
                                     mode: Mode::Immediate,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xEA,
                                     name: Name::NOP,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xEC,
                                     name: Name::CPX,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xED,
                                     name: Name::SBC,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xEE,
                                     name: Name::INC,
                                     mode: Mode::Absolute,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xF0,
                                     name: Name::BEQ,
                                     mode: Mode::Relative,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xF1,
                                     name: Name::SBC,
                                     mode: Mode::IndirectY,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xF5,
                                     name: Name::SBC,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xF6,
                                     name: Name::INC,
                                     mode: Mode::ZeroPageX,
                                     bytes: 2,
                                 },
                                 Opcode {
                                     code: 0xF8,
                                     name: Name::SED,
                                     mode: Mode::Implied,
                                     bytes: 1,
                                 },
                                 Opcode {
                                     code: 0xF9,
                                     name: Name::SBC,
                                     mode: Mode::AbsoluteY,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xFD,
                                     name: Name::SBC,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 },
                                 Opcode {
                                     code: 0xFE,
                                     name: Name::INC,
                                     mode: Mode::AbsoluteX,
                                     bytes: 3,
                                 }];

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_get_by_code_when_present() {
        let opcode = Opcode::get_by_code(0x00).unwrap();
        match opcode.name {
            Name::BRK => assert!(true),
            _ => assert!(false),
        }
    }

    #[test]
    fn test_get_by_code_when_not_present() {
        assert!(Opcode::get_by_code(0xFF).is_none());
    }
}
